# Generated by Django 5.0.1 on 2024-03-05 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at'], 'verbose_name': 'Post Comment', 'verbose_name_plural': 'Post Comments'},
        ),
    ]
